# This workflow will run static type checking on all source files

name: type checking
on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: mypy
    steps:
    - uses: actions/checkout@v2
      with:
        path: dials
    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9  # keep in sync with the default version
    - name: Install dependencies
      run: |
        pip install mypy==0.910  # keep in sync with /.pre-commit-config.yaml
    - name: Run type checking
      run: |
        mypy --no-strict-optional --ignore-missing-imports dials/
